export interface CandidateIdentity {
  firstName?: string;
  lastName?: string;
  displayName?: string;
  name?: string;
  initials?: string;
}

export const getCandidateDisplayName = (candidate?: CandidateIdentity | null) => {
  if (!candidate) return 'Unknown';

  const fullName = [candidate.firstName, candidate.lastName]
    .filter(Boolean)
    .join(' ')
    .trim();

  return fullName || candidate.displayName || candidate.name || 'Unknown';
};

export const getCandidateInitials = (candidate?: CandidateIdentity | null) => {
  if (!candidate) return '?';

  const initials = [candidate.firstName, candidate.lastName]
    .filter((part): part is string => typeof part === 'string' && Boolean(part.trim()))
    .map((part) => part.trim().charAt(0))
    .filter(Boolean)
    .join('')
    .slice(0, 2)
    .toUpperCase();

  if (initials) {
    return initials;
  }

  return candidate.initials || getCandidateDisplayName(candidate).charAt(0).toUpperCase() || '?';
};

export const getEvaluationModeLabel = (evaluationMode?: string) => {
  if (evaluationMode === 'local-fallback') {
    return 'Local fallback';
  }

  return 'Gemini';
};

export const getScreeningModeSummary = (screeningMode?: string | null) => {
  if (screeningMode === 'local-fallback') {
    return {
      eyebrow: 'Fallback Ranking',
      message: 'Gemini quota was unavailable for this screening run. These shortlist results were generated by the local fallback scorer and should be recruiter-reviewed before outreach.',
    };
  }

  if (screeningMode === 'hybrid') {
    return {
      eyebrow: 'Hybrid Ranking',
      message: 'Gemini evaluated part of this shortlist. The remaining candidates were filled in by the local fallback scorer after quota limits were reached.',
    };
  }

  return {
    eyebrow: 'Gemini Ranking',
    message: 'Top shortlisted candidates ranked by Gemini AI analysis.',
  };
};
